Fix string termination in BadPattern exception message
Following largely the same approach as #1, this patch fixes the improper
string termination formerly performed for `BadPattern` exception
messages, which are sourced from `pcre2_get_error_message()`. It also
increases the size of the buffer into which these error messages are
copied, choosing the same constant of `256` as used by most other
open-source projects (as found by a quick survey of uses of this
function on GitHub): currently, the maximum length of any of PCRE2's
error messages is [92 bytes](https://github.com/PCRE2Project/pcre2/blob/master/src/pcre2_error.c#L134)
including the null terminator, so this change moves us well out of the
range of our buffer being too small.

Prior to this patch:
```ocaml
utop # Pcre2.regexp "(";;
Exception:
Pcre2.Error
 (Pcre2.BadPattern
   ("missing closing parenthesis\000\001\000\000\000\001\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\000\b\000\000\000\000\000\000\x90»\x8F\004\001\000\000\000\003\000\000\000\000\000\000\000ü\004\000\000\000\000\000\000A\000\000\000\000\000\000\006\000\004\000\000\000\000\000\000",
   1)).
```

With this patch:
```ocaml
utop # Pcre2.regexp "(";;
Exception: Pcre2.Error (Pcre2.BadPattern ("missing closing parenthesis", 1)).
```